---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: clinch-home-runner
spec:
  replicas: 2
  template:
    spec:
      repository: clincha/clinch-home
      image: clincha/build-agent-ubuntu:latest
      env: []