name: build-agents

on:
  push:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Docker Build, Tag & Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: clincha/build-agent-ubuntu
          tags: latest, v1.0
          registry: docker.io
          dockerfile: ubuntu/Dockerfile
          directory: ubuntu
          username: clincha
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-agents-clinch-home:
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create kubeconfig file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./kubeconfig
          contents: ${{ secrets.KUBECONFIG }}
          write-mode: overwrite

      - name: kubectl
        run: kubectl apply -f ./deployments/ --kubeconfig ./kubeconfig